title: Rafael Gomes de Oliveira
author: rthealien
description: >- # this means to ignore newlines until "baseurl:"
    Mais uma tentativa de blog, com um misto de página pessoal, portfólio, etc
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rafaelgoliveira.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rthealien
github_username:  rthealien
lang: "pt-BR"
paginate: 3
paginate_path: "/pagina:num/"
mastodon_url: "https://ursal.zone/@rthealien"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

minima:
  date_format: "%d-%m-%Y"
  
